version: '3'

services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_DB: aluraloja
      POSTGRES_USER: alura
      POSTGRES_PASSWORD: alura
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "54321:80"
    depends_on:
      - postgres
